name: testing release

on:
  push:
    branches:
      - beta
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      attestations: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04-arm
            name: Raspberry Pi 5 (ARM64)
            # Added 'yasm' to satisfy the CMake check and 'libva-dev' for hardware acceleration support
            install: |
              sudo apt-get update
              sudo apt-get install -y libasound2-dev libgl-dev libglu1-mesa-dev libgtk-3-dev libjack-dev libmad0-dev libpulse-dev libudev-dev libxinerama-dev libx11-dev libxrandr-dev libxtst-dev yasm libva-dev libjpeg-dev
            release: |
              cmake -B build -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_FLAGS="-mcpu=cortex-a76" \
                -DCMAKE_CXX_FLAGS="-mcpu=cortex-a76" \
                -DWITH_FULL_RELEASE=Off \
                -DWITH_NIGHTLY_RELEASE=On \
                -DWITH_CLUB_FANTASTIC=Off \
                -DWITH_MINIMAID=Off \
                -DWITH_FFMPEG_JOBS="$(nproc)"
              cmake --build build --target package
            path: build/ITGmania-*-NIGHTLY-git-*-Linux-aarch64-no-songs.tar.gz

    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache CMake build directory
        uses: actions/cache@v4
        with:
          path: |
            build/*
            !${{ matrix.path }}
          key: ${{ runner.os }}-${{ runner.arch }}-cmake-build-nightly-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-cmake-build-nightly-

      - name: Install dependencies
        if: matrix.os != 'windows-latest'
        run: ${{ matrix.install }}

      - name: Add msbuild to PATH
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Create release
        run: ${{ matrix.release }}

      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ITGmania-${{ github.sha }}-${{ matrix.name }}
          path: ${{ matrix.path }}
          compression-level: 0

      - uses: actions/attest-build-provenance@v2
        with:
          subject-name: ITGmania-${{ github.sha }}-${{ matrix.name }}
          subject-digest: sha256:${{ steps.upload.outputs.artifact-digest }}
